### ISSUE TITLE
ArgumentError when reaching lock_timeout?

### ISSUE THREAD

**Issue by demental** [joel/resque-async-method-enhanced#6]
```
ArgumentError: wrong number of arguments (3 for 0)
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-lock-timeout-0.4.1/lib/resque/plugins/lock_timeout.rb:118:in `locked?'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-lock-timeout-0.4.1/lib/resque/plugins/lock_timeout.rb:150:in `before_enqueue_lock'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-1.23.0/lib/resque.rb:236:in `block in enqueue_to'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-1.23.0/lib/resque.rb:235:in `collect'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-1.23.0/lib/resque.rb:235:in `enqueue_to'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-1.23.0/lib/resque.rb:221:in `enqueue'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/resque-async-method-enhanced-1.3.2/lib/resque/plugins/async/method.rb:26:in `block in async_method'
    from /Users/demental/Sites/ror/tonpsy.com/app/state_machines/consultation_state_machine.rb:57:in `block (4 levels) in <module:ConsultationStateMachine>'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/eval_helpers.rb:77:in `call'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/eval_helpers.rb:77:in `evaluate_method'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/callback.rb:191:in `block in run_methods'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/callback.rb:190:in `each'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/callback.rb:190:in `run_methods'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/callback.rb:159:in `call'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/transition.rb:443:in `block (2 levels) in after'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/transition.rb:443:in `each'
... 34 levels...
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:147:in `run_actions'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:60:in `perform'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/transition.rb:212:in `perform'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/event.rb:167:in `fire'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/event.rb:236:in `block in add_actions'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `call'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `block (2 levels) in define_helper'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/event.rb:241:in `block in add_actions'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `call'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `block (2 levels) in define_helper'
    from (irb):2
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/demental/.rvm/gems/ruby-1.9.3-p286@tonspy/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'

```

**Comment by demental** [comment]
I'll try to isolate the problem on a fresh, minimal project
